import './../../styles/globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Providers from '@/components/Providers'
import { Suspense } from 'react'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
          <Providers>
              <Navbar />
              <Suspense fallback={(<h1>Loading...</h1>)}>
                {children} 
              </Suspense>
              <Footer />
          </Providers>
        </body>
    </html>
  )
}
